[package]
name = "anzu-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1"
winit = { version = "0.30.8", features = ["rwh_06"]  }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [ "fmt", "time" ] }
wgpu = "24.0.1"
futures = "0.3.31"

[lib]
path = "src/app/mod.rs"
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0"
tracing-wasm = "0.2.1"
wgpu = { version = "24.0.1", features = ["webgl"]}
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = [
    "Document",
    "Window",
    "Element",
]}
